[book]
language = "uk"
multilingual = false
src = "docs"

authors = ["Davyd \"DavidkJun\" Krykota", "Veronika \"nikama-s\" Maslo","Veronica  \"namanica\" Pylypchuk", "Illia \"yur-ochka \" Yurchenko", "Kyryl \"Kiryaoo \" Kozarezov ", "Tymur \"Homa4\" Naboka", " Aryna \"nevsetakpohano\" Babanina"]



title = "Організація та управління опитуваннями для експертів"
[preprocessor.plantuml]
plantuml-cmd = "http://www.plantuml.com/plantuml"
use-data-uris = true
